name: 构建IYUUPlus镜像
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*-beta*'
      - 'v*-rc*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建iyuuplus-dev
    env:
      IMAGE_NAME: iyuuplus-dev
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Verify and Create Cache Paths
        run: |
          mkdir -p /tmp/.buildx-cache

      - name: Set Up Cache
        uses: actions/cache@v3
        id: buildx-cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-
          
      - name: Buildx
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          file: docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_NAME }}/${{ env.IMAGE_NAME }}:latest
